### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by siniseong** [tlsgmltjd/hello-blog#1]
저 기억하시나요...? 부소마고에 신희성입니다. 이야기를 해보고 싶었는데 SNS에 대해서의 정보가 없어서 Issues에 글 남겨봅니당
제 인스타그램은 huise0ng입니다. 시간되실때 한번 팔로우 걸어주세용 ~ 그리고 이 이슈는 지우셔도 됨니당

**Comment by vumrra** [comment]
❤️

**Comment by siniseong** [comment]
Thank you
